[package]
name = "cuda-kernels"
version = "0.1.0-dev"
description = ""
license = "MIT OR Apache-2.0"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"

[dependencies]

[build-dependencies]
cmake = "0.1"
