[workspace]
members = ["crates/*"]

[workspace.dependencies]
maiden-cuda_cuda-core = { path = "crates/cuda-core", version = "0.1.0-dev" }
maiden-cuda_cuda-kernels = { path = "crates/cuda-kernels", version = "0.1.0-dev" }
maiden-cuda_cuda-sys = { path = "crates/cuda-sys", version = "0.1.0-dev" }
maiden-cuda_tensor = { path = "crates/tensor", version = "0.1.0-dev" }

[package]
name = "maiden-cuda"
version = "0.1.0-dev"
description = "CUDA implementation for Maiden Engine"
license = "MIT OR Apache-2.0"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"
publish = true
repository = "https://github.com/miniex/maiden-cuda"
documentation = "https://docs.rs/maiden-cuda"
readme = "README.md"
keywords = ["cuda", "gpu", "maiden"]
categories = ["science", "gpu"]

[dependencies]
maiden-cuda_tensor = { workspace = true }
