[package]
name = "maiden_cuda-sys"
version = "0.0.1"
description = "Maiden CUDA System"
license = "MIT OR Apache-2.0"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"

[dependencies]
libc = "0.2"
